In [70]:
# Manipulate json files
import json
# Manipulate dataframes
import pandas as pd
# For saving the response data in CSV format
import csv

# Define rootpath
rp = 'C:\\Users\\sgmmahon\\Documents\\GitHub\\iom_project\\'
mp = 'methods\\accessing_tweets\\'
dp = 'data\\tweet_data\\' 

# Define file pathway
pathway = rp + dp + 'tweets/ukraine_refugees_2022.csv'

In [71]:
# Load in json file
with open(rp + dp + 'tweets/ukraine-refugees_2022.json') as f:
   data = json.load(f)

In [89]:
# Create empty pandas dataframe with correct column titles
migr = pd.DataFrame(columns = pd.concat([pd.DataFrame(data['data'][0]).drop('population_groups', axis=1),
                                         pd.DataFrame(data['data'][0]['population_groups']).drop(columns=['id','name'], axis=1),
                                         pd.DataFrame(data).drop('data', axis=1)], axis=1).columns.values.tolist())

# For loop which extracts data from different levels of json file and appends to migr
for country in data['data']:
    # Extract data at different nested levels into separate dataframes
    cols1 = pd.DataFrame(country).drop('population_groups', axis=1)
    cols2 = pd.DataFrame(country['population_groups']).drop(columns=['id','name'], axis=1)
    cols3 = pd.DataFrame(data).drop('data', axis=1).iloc[0:1]
    # Append data to migr dataframe
    migr = migr.append(pd.concat([cols1, cols2, cols3],axis=1))
    
# Reset dataframe index
migr = migr.rename(columns={'population_groups_concat': 'population_group_name'}).reset_index().drop('index',axis=1)

# Save as csv
migr.to_csv(pathway)

# Show results
migr

,geomaster_name,geomaster_id,admin_level,centroid_lon,centroid_lat,lat_max,lon_max,lat_min,lon_min,source,...,title_language_es,title_language_fr,subtitle_language_ar,subtitle_language_en,subtitle_language_es,subtitle_language_fr,limit,color,frequency,chartType
0,Poland,10781,Country,19.4013,52.1224,55.469506,26.401300,48.021549,12.401300,None,...,,,,,,,,#3c8dbc,day,areaspline
1,Hungary,10783,Country,19.4131,47.1672,54.167200,26.588881,43.760061,12.413100,None,...,,,,,,,,#3c8dbc,day,areaspline
2,Republic of Moldova,10784,Country,28.4646,47.1976,54.197600,35.464600,40.197600,21.464600,None,...,,,,,,,,#3c8dbc,day,areaspline
3,Other European countries,10792,Settlement,12.999541505426,49.284734814307,51.315890,19.828251,47.368175,14.696223,None,...,,,,,,,,#3c8dbc,day,areaspline
4,Slovakia,10785,Country,19.4864,48.7062,55.706200,26.486400,41.706200,12.486400,None,...,,,,,,,,#3c8dbc,day,areaspline
5,Romania,10782,Country,25.3,45.8667,52.866700,32.300000,38.866700,18.300000,None,...,,,,,,,,#3c8dbc,day,areaspline
6,Russian Federation,10791,Country,38.1556078125,51.488850139616,59.067055,36.958298,54.998769,31.669526,None,...,,,,,,,,#3c8dbc,day,areaspline
7,Belarus,10786,Country,28.0463,53.5384,57.838934,33.727941,48.496894,21.046300,None,...,,,,,,,,#3c8dbc,day,areaspline